name: tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        php: [ '8.3' ]
        laravel: [ '11.45' ]
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Installing PHP
        uses: shivammathur/setup-php@main
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Shutting down MySQL
        run: sudo service mysql stop
      - name: Installing MariaDb
        uses: YakkaDev/mariadb-actions@v1.1.0
        with:
          character: 'utf8mb4'
          version: '10.6.18'
          database: 'tw_testdb'
          user: 'tw_testuser'
          password: 'z0rglub'
      - name: Lock Laravel Version
        run: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: 'tw_testdb'
          DB_USERNAME: 'tw_testuser'
          DB_PASSWORD: 'z0rglub'
      - name: Install NPM packages
        run: npm install --verbose
      - name: Build assets
        run: npm run build
      - name: Create and fill database
        run: php artisan migrate --seed --seeder CywiseSeeder
        env:
          APP_ENV: testing
          APP_KEY: 'base64:YZzRGIAPQgqSLZBJ7rILm7B05FfdvxSBaHVoQFzBuS0='
          ADMIN_EMAIL: qa@computablefacts.com
          ADMIN_USERNAME: qa
          ADMIN_PASSWORD: whatapassword
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          QUEUE_DRIVER: sync
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: 'tw_testdb'
          DB_USERNAME: 'tw_testuser'
          DB_PASSWORD: 'z0rglub'
          DROP_SCAN_EVENTS_AFTER_X_MINUTES: 1
          DROP_DISCOVERY_EVENTS_AFTER_X_MINUTES: 1
          DAYS_BETWEEN_SCANS: 5
      - name: Remove checksum for migration
        run: rm -f storage/app/migration-checksum_tw-testdb.txt
      - name: Remove checksum for seeder
        run: rm -f storage/app/seeder-checksum_tw-testdb.txt
      - name: Run Unit Tests
        run: php vendor/bin/pest -c phpunit.xml --testdox
        env:
          DROP_SCAN_EVENTS_AFTER_X_MINUTES: 0.5
          DROP_DISCOVERY_EVENTS_AFTER_X_MINUTES: 0.5